name: bimanual_mv

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    "scene_13": &camera_meta
      # (c, h, w)
      shape: [3, 256, 320]
      type: rgb
    "scene_14": *camera_meta
    "scene_15": *camera_meta
    "scene_16": *camera_meta


    "robot__actual__poses__right::panda__xyz":
      shape: [3]
      type: low_dim
    "robot__actual__poses__right::panda__rot_6d":
      shape: [6]
      type: low_dim
    "robot__actual__poses__left::panda__xyz":
      shape: [3]
      type: low_dim
    "robot__actual__poses__left::panda__rot_6d":
      shape: [6]
      type: low_dim
    "robot__actual__grippers__right::panda_hand":
      shape: [1]
      type: low_dim
    "robot__actual__grippers__left::panda_hand":
      shape: [1]
      type: low_dim

    "robot__desired__poses__right::panda__xyz":
      shape: [3]
      type: low_dim
    "robot__desired__poses__right::panda__rot_6d":
      shape: [6]
      type: low_dim
    "robot__desired__poses__left::panda__xyz":
      shape: [3]
      type: low_dim
    "robot__desired__poses__left::panda__rot_6d":
      shape: [6]
      type: low_dim
    "robot__desired__grippers__right::panda_hand":
      shape: [1]
      type: low_dim
    "robot__desired__grippers__left::panda_hand":
      shape: [1]
      type: low_dim

  action:
    # (3(pos) + 6(rot) + 1(gripper))*2
    shape: [20]

task_name: &task_name bimanual_video_gen
dataset_path: &dataset_path [
  # NEEDS OVERWRITE: add episode folders here, for example:
  /fsx-siro/liuzeyi/4dgen/data/BimanualStoreCerealBoxUnderShelf/2025-03-13T04-19-57+00-00/diffusion_spartan/episode_*
  ]

dataset:
  _target_: dataset.spartan_video_dataset.SpartanVideoMultiViewDataset
  episode_path_globs: *dataset_path
  stride: 5
  horizon: ${horizon}
  pad_before: 0
  pad_after: 0
  shape_meta: *shape_meta
  rotation_rep: rotation_6d
  repeat_head: 0
  repeat_tail: 0  # for repeating
  has_gripper: false  # we use separate codepath for this
  has_depth: true
  has_label: true
  val_ratio: 0.1
  # policy handles normalization
  imagenet_normalization: False

  mode: "zarr"
  replay_buffer_path: /fsx-siro/liuzeyi/4dgen/data/single_task/store_cereal_box_under_shelf/replay_buffer_infer.zarr

  compressor: "blosc"
  is_multiarm: true
  num_workers: 16
  raw_rgb: false
  apply_static_filter: true
  